### ISSUE TITLE
rev OB 0.5 assertion validation fails with no graph or message

### ISSUE THREAD

**Issue by cawmichael** [IMSGlobal/openbadges-validator-core#181]
I have only seen this for a version 0.5 Assertion.
Excerpt from result:

```
'graph': [],
'report':  {'errorCount': 0, 'warningCount': 0, 'messages': [], 'valid': False}
```

While the validation has been flagged as 'False', the above provides no indication of where the issue with the Assertion may be.  If there is a problem with the JSON or any related data one would expect it to show in the messages.

**Comment by ottonomy** [comment]
@cawmichael can you provide the input you used? I'll try to reproduce, but it would be helpful to know specifically what you used so I can make sure the new tests cover that case.

**Comment by cawmichael** [comment]
@ottonomy here is the assertion(unformatted) and the baked image.  It is an old one from CodeSchool.
`
{'badge': {'name': 'Completed Rails for Zombies Redux', 'description': 'Awarded for the completion of Rails for Zombies Redux', 'version': '0.5.0', 'issuer': {'org': None, 'contact': None, 'name': 'Code School', 'origin': 'http://www.codeschool.com'}, 'image': 'https://d1ffx7ull4987f.cloudfront.net/images/achievements/large_badge/133/completed-rails-for-zombies-redux-0f73c361c3d5070ca2fa7951e65cbf39.png', 'criteria': 'https://www.codeschool.com/users/mrmickca/badges/133'}, 'issued_on': '2012-12-28', 'salt': '6abf7e9504d73363bdcf9336056f5235', 'verify': {'type': 'hosted', 'url': 'https://www.codeschool.com/users/mrmickca/badges/133/assertion'}, 'recipient': 'sha256$ef1253755797c2a3dfd3ab455a7a2080cb9160f2f1fbbf99c475347af1ecc598'}
`

![4f7fcb4f609453f4d14939bed31a0ac05b69440320bb17b1a14591a3d816d92e](https://user-images.githubusercontent.com/17549774/31668398-19ba8a58-b320-11e7-89e0-f0a06a02f9e7.png)

**Comment by ottonomy** [comment]
That badge is invalid because "Response could not be interpreted from url https://www.codeschool.com/users/mrmickca/badges/133/assertion " (Codeschool gave up on Open Badges a couple years ago I think. This is no longer an open badge." ... The correct error message is achieved by url input of the assertion URL. 

Additionally, this assertion is a bastardization of 0.5 and 1.0. It contains the 1.0 "verify" structure that was not present in the 0.5 spec, but it uses the 0.5 "badge" and "issuer" structures. I'll see if I can make the validator yield the correct input from JSON or image input as well.

**Comment by ottonomy** [comment]
Remarkably, this is one of the few instances where the "version" property was correctly used as it was designed in the 0.5 spec. This isn't the current way we're using version, so if this were a valid badge, this would be properly stripped out upon upgrade from 0.5 to 1.1 (one of the steps in the process).  I'll submit a PR that properly reports what fails about this badge if you give it JSON or image input.
