### ISSUE TITLE
Pycrypto appears unused and is causing build issues

### ISSUE THREAD

**Issue by SecondFlight** [IMSGlobal/openbadges-validator-core#193]
I've been trying to install the latest code into my Python 3.6 environment. Setup.py fails when installing pycrypto due to a build error for a required C library.

![image](https://user-images.githubusercontent.com/6700184/35992116-5df57a0a-0cd7-11e8-90c2-7444398ff388.png)

After some digging, I found two things:

1. Pycrypto is completely unsupported and hasn't been developed for over 3 years. It's been recommended to switch to PyCryptodome, which is an active fork and almost a drop-in replacement. See [this issue](https://github.com/dlitz/pycrypto/issues/238) on the pycrypto github page for more info.

2. As far as I can tell, pycrypto isn't used anywhere in the project. This is based on a search I did of the badgecheck repo for "pycrypto", which only came up with requirements.txt and setup.py, which are just dependency lists. I would assume that there would be an import for pycrypto if it were used.

**Comment by ottonomy** [comment]
Thanks, @SecondFlight 

The tool is used by our dependency jws, so in order to remove it from the project, it will have to also be removed from [jws](https://github.com/brianloveswords/python-jws). Totally possible, and thanks for bringing this up.

It appears in import statements like `from Crypto.PublicKey import RSA`, which are used in our tests to generate the signing keys etc that we then check with the jws module.

If you have time to commit to submitting a PR, let us know, otherwise @mgylling will look for a volunteer among the IMS membership. I might be able to do it myself in the next week or two, as Concentric Sky makes a little of my time available for maintaining this package.

**Comment by SecondFlight** [comment]
Thanks for the reply, @ottonomy.

Unfortunately, the project I'm working on won't allow time to work on this, and I don't think I'll be able to find time to commit to this outside of work hours.

I should mention, I was able to get it to install by simply removing the reference to pycrypto. This would make sense if pycrypto is only used for the unit tests.

I appreciate all the work you folks have done for this project! Sorry I can't help more.
