### ISSUE TITLE
Valid: True  This badge passed all verification checks BUT also said Recipient Not Verified: In order to test whether this badge has been awarded to the person or entity you expect, enter their profile data on the submission form.

### ISSUE THREAD

**Issue by haducloc** [IMSGlobal/openbadges-validator-core#198]
I had a JWT that contains signed badge. The below is it:

eyJhbGciOiAicnMyNTYiLCAidHlwIjogIkpXVCJ9.ewogICJAY29udGV4dCI6ICJodHRwczovL3czaWQub3JnL29wZW5iYWRnZXMvdjIiLAogICJpZCI6ICJ1cm46dXVpZDo5Mzk3YWZiYy1hZTNjLTQyOTgtOWNmYy02NGE4OGVhMmUwNDMiLAogICJ0eXBlIjogIkFzc2VydGlvbiIsCiAgInJlY2lwaWVudCI6IHsKICAgICJpZGVudGl0eSI6ICJzaGEyNTYkMzJiZDA2YTQ3NGQzOTYxNGI5OTNmNjExZDdiNmI0MDMxOTk0Y2FkMjZmYmQ3ZTY0Zjg5MmJkMjlmYjQ2Mjg3YiIsCiAgICAidHlwZSI6ICJlbWFpbCIsCiAgICAiaGFzaGVkIjogdHJ1ZSwKICAgICJzYWx0IjogIjhmNGY3YWIzYTlkYWE2NWUxMTRhOWZhMGQ1MDA0NzQzIgogIH0sCiAgImJhZGdlIjogewogICAgImlkIjogImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9oYWR1Y2xvYy9vYi9tYXN0ZXIvdW5iYWtlX2JhZGdlLnBuZyIsCiAgICAidHlwZSI6ICJCYWRnZUNsYXNzIiwKICAgICJuYW1lIjogIkJhZGdlMSIsCiAgICAiZGVzY3JpcHRpb24iOiAiRGVzY3JpcHRpb24xIiwKICAgICJpbWFnZSI6ICJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vaGFkdWNsb2Mvb2IvbWFzdGVyL3VuYmFrZV9iYWRnZS5wbmciLAogICAgImNyaXRlcmlhIjogImh0dHBzOi8vZ2l0aHViLmNvbS9oYWR1Y2xvYy9vYiIsCiAgICAiaXNzdWVyIjogewogICAgICAidHlwZSI6ICJQcm9maWxlIiwKICAgICAgImlkIjogImh0dHBzOi8vZ2l0aHViLmNvbS9oYWR1Y2xvYyIsCiAgICAgICJuYW1lIjogIklzc3VlcjEiLAogICAgICAidXJsIjogImh0dHBzOi8vZ2l0aHViLmNvbS9oYWR1Y2xvYyIsCiAgICAgICJlbWFpbCI6ICJpc3N1ZXJAZ21haWwuY29tIgogICAgfQogIH0sCiAgInZlcmlmaWNhdGlvbiI6IHsKICAgICJ1cmwiOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL2hhZHVjbG9jL29iL21hc3Rlci9wdWIucGVtIiwKICAgICJ0eXBlIjogInNpZ25lZCIKICB9LAogICJpc3N1ZWRPbiI6ICIyMDE4LTAzLTIzVDE0OjQ3OjU4LjQ0OS0wNTowMCIsCiAgImV2aWRlbmNlIjogImh0dHBzOi8vZ2l0aHViLmNvbS9oYWR1Y2xvYy9vYiIKfQ==.i-_zrDsFeV1zGlNYG3DxiouiOqnxP43yvCkPLY7hGa04uQtpYzMQ19ScuRIzIQfsDk-nvvrWxLE7emPVI6QXCC3QLYOHxKXYqq_E2ig98UMiUarWy_qPVzakBCQOnwyMqyxXPwsFg7JHJHGU4XOO_AC2cRqxFjmR_7dRFz3qA3JoqyBBdVzuAo0Z3SanOxUJleIlVgwwB6R5P1iaVqV1A5oBMzhSBKYntZ-dDW9rPSN20HPjf_lFBh-PBOSHfxyfSuUrlA1qm8q84DBrowXQEi1WqNxgNIzIDq4mKiAdtLEJRJNiqL7oT1seN1p7W5Pn_Mfa_r2OruW1Ew3j0yj8ig==

I got message Valid & Recipient Not Verified. Please tell me what is wrong? Thanks!

**Comment by ottonomy** [comment]
The verification of a recipient is an optional component of verifying an assertion. In order to do so, you need to send in a potential recipient profile to test, like: 
```json
{
   "email": ["someemail@example.com", "myotheremail@example.com"],
   "url": "http://someurl.example.com/that-a-user-might-be-awarded-a-badge-at"
}
```
(Context and type omitted, if not present they will be automatically inserted by the validator)
If you do, the identifiers included in the recipient profile will be checked against the identity string `u'sha256$32bd06a474d39614b993f611d7b6b4031994cad26fbd7e64f892bd29fb46287b' in the badge. 

If you don't include a profile, your badge assertion might be a valid assertion structurally, but the inspector will not be able to reach any conclusions about whether or not a particular possible recipient actually is the recipient.

I'm seeing a couple other issues with this badge, but this should be enough to get you moving again. (The next thing noted was the `id` property of the embedded BadgeClass appears to be targeting a PNG instead of JSON(-LD).
